<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.success_handler.main.form_login' shared service.

$this->privates['security.authentication.success_handler.main.form_login'] = $instance = new \Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler(($this->privates['security.http_utils'] ?? $this->load('getSecurity_HttpUtilsService.php')), [], ($this->privates['monolog.logger'] ?? $this->load('getMonolog_LoggerService.php')));

$instance->setOptions(['login_path' => 'login', 'always_use_default_target_path' => true, 'default_target_path' => '/', 'target_path_parameter' => '_target_path', 'use_referer' => false]);
$instance->setProviderKey('main');

return $instance;
