<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEkjlhNX\appAppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEkjlhNX/appAppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerEkjlhNX.legacy');

    return;
}

if (!\class_exists(appAppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerEkjlhNX\appAppKernelTestDebugContainer::class, appAppKernelTestDebugContainer::class, false);
}

return new \ContainerEkjlhNX\appAppKernelTestDebugContainer([
    'container.build_hash' => 'EkjlhNX',
    'container.build_id' => '6d9d4598',
    'container.build_time' => 1673342134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEkjlhNX');
