<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'homepage' => [[], ['_controller' => 'AppBundle\\Controller\\DefaultController::indexAction'], [], [['text', '/']], [], []],
    'login' => [[], ['_controller' => 'AppBundle\\Controller\\SecurityController::loginAction'], [], [['text', '/login']], [], []],
    'login_check' => [[], ['_controller' => 'AppBundle\\Controller\\SecurityController::loginCheck'], [], [['text', '/login_check']], [], []],
    'logout' => [[], ['_controller' => 'AppBundle\\Controller\\SecurityController::logoutCheck'], [], [['text', '/logout']], [], []],
    'task_list' => [[], ['_controller' => 'AppBundle\\Controller\\TaskController::listAction'], [], [['text', '/tasks']], [], []],
    'task_create' => [[], ['_controller' => 'AppBundle\\Controller\\TaskController::createAction'], [], [['text', '/tasks/create']], [], []],
    'task_edit' => [['id'], ['_controller' => 'AppBundle\\Controller\\TaskController::editAction'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/tasks']], [], []],
    'task_toggle' => [['id'], ['_controller' => 'AppBundle\\Controller\\TaskController::toggleTaskAction'], [], [['text', '/toggle'], ['variable', '/', '[^/]++', 'id'], ['text', '/tasks']], [], []],
    'task_delete' => [['id'], ['_controller' => 'AppBundle\\Controller\\TaskController::deleteTaskAction'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id'], ['text', '/tasks']], [], []],
    'user_list' => [[], ['_controller' => 'AppBundle\\Controller\\UserController::listAction'], [], [['text', '/users']], [], []],
    'user_create' => [[], ['_controller' => 'AppBundle\\Controller\\UserController::createAction'], [], [['text', '/users/create']], [], []],
    'user_edit' => [['id'], ['_controller' => 'AppBundle\\Controller\\UserController::editAction'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/users']], [], []],
];
