<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'homepage' => [[], ['_controller' => 'App\\Controller\\DefaultController::indexAction'], [], [['text', '/']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::loginAction'], [], [['text', '/login']], [], []],
    'login_check' => [[], ['_controller' => 'App\\Controller\\SecurityController::loginCheck'], [], [['text', '/login_check']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logoutCheck'], [], [['text', '/logout']], [], []],
    'task_list' => [[], ['_controller' => 'App\\Controller\\TaskController::listAction'], [], [['text', '/tasks']], [], []],
    'task_create' => [[], ['_controller' => 'App\\Controller\\TaskController::createAction'], [], [['text', '/tasks/create']], [], []],
    'task_edit' => [['id'], ['_controller' => 'App\\Controller\\TaskController::editAction'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/tasks']], [], []],
    'task_toggle' => [['id'], ['_controller' => 'App\\Controller\\TaskController::toggleTaskAction'], [], [['text', '/toggle'], ['variable', '/', '[^/]++', 'id'], ['text', '/tasks']], [], []],
    'task_delete' => [['id'], ['_controller' => 'App\\Controller\\TaskController::deleteTaskAction'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id'], ['text', '/tasks']], [], []],
    'user_list' => [[], ['_controller' => 'App\\Controller\\UserController::listAction'], [], [['text', '/users']], [], []],
    'user_create' => [[], ['_controller' => 'App\\Controller\\UserController::createAction'], [], [['text', '/users/create']], [], []],
    'user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::editAction'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/users']], [], []],
];
