<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmLfRDC\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmLfRDC/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUmLfRDC.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUmLfRDC\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerUmLfRDC\appAppKernelDevDebugContainer([
    'container.build_hash' => 'UmLfRDC',
    'container.build_id' => '2d4eed7c',
    'container.build_time' => 1673281020,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmLfRDC');
