<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZTnOjx0\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZTnOjx0/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZTnOjx0.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZTnOjx0\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerZTnOjx0\appAppKernelDevDebugContainer([
    'container.build_hash' => 'ZTnOjx0',
    'container.build_id' => 'b4e20f60',
    'container.build_time' => 1673282112,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZTnOjx0');
