<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRQbbWvr\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRQbbWvr/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRQbbWvr.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRQbbWvr\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerRQbbWvr\appAppKernelDevDebugContainer([
    'container.build_hash' => 'RQbbWvr',
    'container.build_id' => 'a5589c0e',
    'container.build_time' => 1673342396,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRQbbWvr');
