<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2eeorbi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2eeorbi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2eeorbi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2eeorbi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2eeorbi\appDevDebugProjectContainer([
    'container.build_hash' => '2eeorbi',
    'container.build_id' => 'efea05a9',
    'container.build_time' => 1673275069,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2eeorbi');
