<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNacmkmn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNacmkmn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNacmkmn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNacmkmn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNacmkmn\appDevDebugProjectContainer([
    'container.build_hash' => 'Nacmkmn',
    'container.build_id' => 'b42adb9b',
    'container.build_time' => 1673272046,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNacmkmn');
