<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYn4T1s7\AppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYn4T1s7/AppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYn4T1s7.legacy');

    return;
}

if (!\class_exists(AppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYn4T1s7\AppKernelDevDebugContainer::class, AppKernelDevDebugContainer::class, false);
}

return new \ContainerYn4T1s7\AppKernelDevDebugContainer([
    'container.build_hash' => 'Yn4T1s7',
    'container.build_id' => '6ba60454',
    'container.build_time' => 1673283347,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYn4T1s7');
